// def/expand and helper-entity tagging for PCS macros.
import {tokenize} from './lexer.js';

export function findMacro(sketch, name) {
    if (!sketch || !Array.isArray(sketch.macros)) {
        console.warn('findMacro: sketch or sketch.macros is undefined or invalid');
        return null;
    }
    if (!name || typeof name !== 'string') {
        console.warn('findMacro: macro name must be a non-empty string, received:', name);
        return null;
    }
    return sketch.macros.find((m) => m.name === name) ?? null;
}

export function defineMacro(sketch, def) {
    if (!sketch) {
        console.error('defineMacro: sketch object is required');
        throw new TypeError('defineMacro: sketch object is required');
    }
    if (!sketch.macros) {
        sketch.macros = [];
    } else if (!Array.isArray(sketch.macros)) {
        console.error('defineMacro: sketch.macros must be an array');
        throw new TypeError('defineMacro: sketch.macros must be an array');
    }
    if (!def || typeof def !== 'object') {
        console.error('defineMacro: def must be a macro definition object, received:', def);
        throw new TypeError('defineMacro: def must be a macro definition object');
    }
    if (typeof def.name !== 'string' || def.name.trim() === '') {
        console.error('defineMacro: macro name must be a non-empty string, received:', def.name);
        throw new Error('defineMacro: macro name must be a non-empty string');
    }
    if (!Array.isArray(def.params)) {
        console.error(`defineMacro: macro '${def.name}' params must be an array, received:`, def.params);
        throw new TypeError(`defineMacro: macro '${def.name}' params must be an array`);
    }
    if (typeof def.body !== 'string') {
        console.error(`defineMacro: macro '${def.name}' body must be a string, received:`, def.body);
        throw new TypeError(`defineMacro: macro '${def.name}' body must be a string`);
    }

    const i = sketch.macros.findIndex((m) => m.name === def.name);
    const record = {name: def.name, params: def.params.slice(), body: def.body};
    if (i >= 0) {
        console.warn(`defineMacro: Overwriting existing macro definition '${def.name}'`);
        sketch.macros[i] = record;
    } else {
        sketch.macros.push(record);
    }
    return record;
}

export function nextMacroInstance(sketch, name) {
    if (!sketch) {
        console.error('nextMacroInstance: sketch object is required');
        throw new TypeError('nextMacroInstance: sketch object is required');
    }
    if (!sketch.macroCalls) {
        sketch.macroCalls = [];
    } else if (!Array.isArray(sketch.macroCalls)) {
        console.error('nextMacroInstance: sketch.macroCalls must be an array');
        throw new TypeError('nextMacroInstance: sketch.macroCalls must be an array');
    }
    if (typeof name !== 'string' || name.trim() === '') {
        console.error('nextMacroInstance: macro name must be a non-empty string, received:', name);
        throw new Error('nextMacroInstance: macro name must be a non-empty string');
    }

    let n = 1;
    while (sketch.macroCalls.some((c) => c && c.id === name + n)) n++;
    return name + n;
}

/**
 * Tag entities generated by a macro call with their macro instance ID.
 */
export function tagHelperEntities(entities, instance) {
    if (!Array.isArray(entities)) {
        console.error('tagHelperEntities: entities must be an array, received:', entities);
        throw new TypeError('tagHelperEntities: entities must be an array');
    }
    if (typeof instance !== 'string' || instance.trim() === '') {
        console.error('tagHelperEntities: instance must be a non-empty string, received:', instance);
        throw new Error('tagHelperEntities: instance must be a non-empty string');
    }
    for (const entity of entities) {
        if (entity && typeof entity === 'object') {
            entity.macroInstance = instance;
            entity.isHelper = true;
        }
    }
    return entities;
}

/**
 * Identifiers declared inside a macro body (`point X …`, `var a, b …`) that
 * are not parameters. They are renamed per instance so helpers don't clash.
 */
export function collectLocals(tokens, params) {
    if (!Array.isArray(tokens)) {
        console.error('collectLocals: tokens must be an array, received:', tokens);
        throw new TypeError('collectLocals: tokens must be an array');
    }
    const paramSet = params instanceof Set ? params : new Set(Array.isArray(params) ? params : []);
    const locals = new Set();
    for (let i = 0; i < tokens.length; i++) {
        const t = tokens[i];
        if (t?.type !== 'ident') continue;
        if (t.value === 'point') {
            const n = tokens[i + 1];
            if (n?.type === 'ident' && !paramSet.has(n.value)) locals.add(n.value);
        } else if (t.value === 'var') {
            let j = i + 1;
            for (; ;) {
                const n = tokens[j];
                if (n?.type !== 'ident') break;
                if (!paramSet.has(n.value)) locals.add(n.value);
                j++;
                while (
                    tokens[j] &&
                    !(tokens[j].type === 'punct' && tokens[j].value === ',') &&
                    tokens[j].type !== 'newline' &&
                    tokens[j].type !== 'eof'
                    )
                    j++;
                if (tokens[j]?.type === 'punct' && tokens[j].value === ',') {
                    j++;
                    continue;
                }
                break;
            }
        }
    }
    return locals;
}

/**
 * Expand a macro body into a token stream with parameters replaced by the
 * call's argument tokens and locals renamed `<instance>_<local>`.
 */
export function expandMacroTokens(def, argTokens, instance) {
    if (!def || typeof def !== 'object') {
        console.error('expandMacroTokens: macro definition must be an object, received:', def);
        throw new TypeError('expandMacroTokens: macro definition must be an object');
    }
    if (typeof def.name !== 'string') {
        console.error('expandMacroTokens: macro definition missing valid name property:', def);
        throw new TypeError('expandMacroTokens: macro definition missing valid name property');
    }
    if (!Array.isArray(def.params)) {
        console.error(`expandMacroTokens: macro '${def.name}' params must be an array, received:`, def.params);
        throw new TypeError(`expandMacroTokens: macro '${def.name}' params must be an array`);
    }
    if (typeof def.body !== 'string') {
        console.error(`expandMacroTokens: macro '${def.name}' body must be a string, received:`, def.body);
        throw new TypeError(`expandMacroTokens: macro '${def.name}' body must be a string`);
    }
    if (!Array.isArray(argTokens)) {
        console.error(`expandMacroTokens: argTokens must be an array for macro '${def.name}', received:`, argTokens);
        throw new TypeError('expandMacroTokens: argTokens must be an array');
    }
    if (typeof instance !== 'string' || instance.trim() === '') {
        console.error(`expandMacroTokens: instance must be a non-empty string for macro '${def.name}', received:`, instance);
        throw new Error('expandMacroTokens: instance must be a non-empty string');
    }
    if (argTokens.length !== def.params.length) {
        const msg = `Macro '${def.name}' expects ${def.params.length} argument(s), but received ${argTokens.length}`;
        console.error(`expandMacroTokens: ${msg}`);
        throw new Error(`expandMacroTokens: ${msg}`);
    }

    let tokens;
    try {
        tokens = tokenize(def.body);
    } catch (err) {
        console.error(`expandMacroTokens: Failed to tokenize macro body for '${def.name}':`, err);
        throw new Error(`expandMacroTokens: Failed to tokenize macro body for '${def.name}': ${err.message}`);
    }

    const paramMap = new Map(def.params.map((p, i) => [p, argTokens[i]]));
    const locals = collectLocals(tokens, new Set(def.params));
    return tokens.map((t) => {
        if (t.type !== 'ident') return t;
        if (paramMap.has(t.value)) {
            const arg = paramMap.get(t.value);
            if (arg && typeof arg === 'object' && 'value' in arg) {
                return {
                    ...t,
                    type: arg.type !== undefined ? arg.type : t.type,
                    value: arg.value
                };
            }
            return {...t, value: String(arg)};
        }
        if (locals.has(t.value)) return {...t, value: `${instance}_${t.value}`};
        return t;
    });
}